version: ~> 1.0

os: linux
dist: bionic

language: node_js
node_js: lts/*

addons:
  chrome: stable

cache:
  yarn: true

script:
  - yarn lint
  - yarn build
  - yarn test:ci
  - yarn lighthouse

after_script:
  - yarn codecov:upload