version: ~> 1.0

os: linux
dist: bionic

language: node_js
node_js: lts/*

cache:
  yarn: true

script:
  - yarn lint
  - yarn build
  - yarn test:coverage

after_script:
  - yarn codecov
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)
